# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Kim Tae Hyeon
title: 신입 개발자
email: thkim704@naver.com
# email_title: Email (Email title override)
phone: 010-4624-7265
# phone_title: Phone (Phone title override)
website: https://github.com/thkim704
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: thkim704

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요 신입 개발자 김태현입니다. 지금까지 진행해왔던 모든 프로젝트들을 통해 의사 소통과 협업과 같은 팀워크 능력을 습득하였습니다. 새로운 도전에 대한 열린 마음과 적극적인 태도를 바탕으로, 제가 그동안 배워온 모든 기술과 인간적 역량을 발휘하여 회사의 성장에 기여하고자 합니다.
    - <mark>생년월일</mark> 2000.02.09
    - <mark>주소</mark> 서울특별시 영등포구

content:
  - title: Skill Stack
    layout: list
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Language
        description: | # this will include new lines to allow paragraphs
          <mark>Java</mark> <mark>JavaScript</mark> <mark>C</mark> <mark>C++</mark> <mark>Python</mark> <mark>HTML</mark> <mark>XML</mark>
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: DataBase
        description: | # this will include new lines to allow paragraphs
          <mark>Oracle</mark> <mark>MySQL</mark> <mark>Firebase</mark>
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Server
        description: | # this will include new lines to allow paragraphs
          <mark>Apache Tomcat</mark>
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Framework
        description: | # this will include new lines to allow paragraphs
          <mark>Spring</mark>
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Environment
        description: | # this will include new lines to allow paragraphs
          <mark>Android Studio</mark> <mark>IntelliJ IDEA</mark> <mark>Eclipse</mark>
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Etc
        description: | # this will include new lines to allow paragraphs
          <mark>JPA</mark> <mark>DOM</mark> <mark>Google Map Platform</mark>
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 이력서 관리 사이트
        link: github.com/thkim704/Resume
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: github.com/thkim704/Resume
          - title:  Presentation for project
            icon: fas fa-file-powerpoint
            url: https://drive.google.com/file/d/13VydbU_RV_wCg2fJBGRLA9GxWavSLHXa/view?usp=sharing
          - title:  video for project
            icon: fas fa-play
            url: https://drive.google.com/file/d/1EDxfL2TciwK9ljYu9O6D5cg0JA5wkyj5/view?usp=sharing
        quote: >
          <mark>HTML</mark> <mark>CSS</mark> <mark>JavaScript</mark> <mark>Spring</mark> <mark>JPA</mark> <mark>MySQL</mark>
        description: | # this will include new lines to allow paragraphs
            - 취업에 도움이 되도록 원활한 이력 관리를 위한 사이트를 구현하는 개인 프로젝트
            - Oven을 이용해 UI/UX 화면 설계, 요구사항에 따라 기능을 상세하게 설계
            - 기획 산출물을 토대로 엔티티와 속성들을 도출해내고, 정규화를 진행하여 ERD를 설계
            - Spring Boot를 사용하여 MVC 모델로 사이트를 구현
            - MySQL을 DB로 사용, 더 효율적이고 일관적으로 데이터를 관리할 수 있도록 Spring Data JPA를 사용.
            - DOM을 사용하여 동적 페이지로 구현
      - layout: top-middle
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Food-Sharing
        link: github.com/thkim704/Food-Sharing
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: github.com/thkim704/Food-Sharing
          - title:  Presentation for project
            icon: fas fa-file-powerpoint
            url: https://drive.google.com/file/d/1BlSqYWhyzamuOk_FcnLxK5ZsPnQUxeod/view?usp=sharing
          - title:  video for project
            icon: fas fa-play
            url: https://drive.google.com/file/d/1-mZGUk4QAgtq6kTC3VBvhzxFBZsgFgTP/view?usp=sharing
        quote: >
          <mark>Java</mark> <mark>XML</mark> <mark>Android Studio</mark> <mark>FireBase</mark> <mark>Google Map Platform</mark>
        description: | # this will include new lines to allow paragraphs
            - 위치 기반 시스템을 활용한 지역 사람들 끼리 음식을 나눌 수 있는 앱을 개발하는 개인 프토젝트 
            - Oven을 이용해 UI/UX 화면 설계 
            - 기능 요구사항을 기반으로 상세한 프로세스 동작 과정을 도출하여 동작흐름도를 설계
            - Android Studio 환경에서 앱을 구현
            - Firebase를 DB로 사용, Google Map Platform API의 geocoding 기능을 사용해 주소 등록 기능을 구현
            - 설계서를 기반으로 체크 리스트를 제작, 이를 통해 테스트를 진행
      - layout: top-middle
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 웹툰 추천 사이트
        link: github.com/thkim704/Webtoon
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: github.com/thkim704/Webtoon
          - title:  Presentation for project
            icon: fas fa-file-powerpoint
            url: https://drive.google.com/file/d/1A6MH0tL-uIRYZjqxyJVnpR9MZ5ybxUds/view?usp=sharing
        quote: >
          <mark>HTML</mark> <mark>CSS</mark> <mark>MySQL</mark> <mark>BootStrap</mark>
        description: | # this will include new lines to allow paragraphs
            - 잊혀져 가거나 숨겨진 웹툰 추천하고 사용자들이 게시판을 이용해 자유롭게 웹툰을 리뷰하는 사이트를 구축하는 팀 프로젝트
            - HTML과 CSS 그리고 JavaScript를 사용하여 총 14개의 화면 중 8개의 화면, 약 17개의 기능 중 11개의 기능을 담당하여 구현 
            - 제가 담당한 주요 기능 : 게시판 기능
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: 인하공업전문대학교
        sub_title: 컴퓨터시스템과 / 학점 ( 3.95 / 4.5 )
        caption: 2018.02 - 2024.02
        quote: >
          인하공업전문대학교는 전 세계 산업현장에서 활발히 활동하고 있는 11만 명 가까운 졸업생을 배출한 명실상부한 대한민국 최고의 전문대학입니다.
        description: | # this will include new lines to allow paragraphs
          저는 대학 시절 동안 팀워크, 촉박한 마감 기한 준수 등 습득한 주요 기술 대부분을 배웠습니다. 모든 활동에 성실히 임한 결과 성공적인 프로젝트 결과물과 준수한 학업 성취를 이룰 수 있었습니다. 이러한 경험을 통해 뛰어난 문제 해결능력과 기획 능력을 갖추게 되었습니다. 특히, 각종 도전과 고난을 극복하면서 자발적이고 적극적인 태도를 키우게 되었습니다. 
  - title: Certificate
    layout: list
    content:
      - layout: top-middle
        title: 정보처리산업기사
        sub_title: 한국산업인력공단
        caption: 2023.11.17.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
